import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StickyNavbar } from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { AppProvider } from "@/contexts/app-context";
import LoginForm from "@/components/auth/login-form";
import SignUpForm from "@/components/auth/signup-form";
import { AuthProvider } from "@/contexts/auth-context";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/contexts/cart-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <AuthProvider>
            <CartProvider>
              <StickyNavbar />
              <div style={{ minHeight: "70vh" }} className="lg:px-40">
                <Toaster
                  position="top-center"
                  containerStyle={{ zIndex: 99999 }}
                  toastOptions={{
                    success: {
                      style: {
                        background: "lightblue",
                      },
                      iconTheme: {
                        primary: "white",
                        secondary: "black",
                      },
                    },
                    error: {
                      style: {
                        background: "palevioletred",
                      },
                    },
                  }}
                />
                {children}
              </div>
              <Footer />
              <LoginForm />
              <SignUpForm />
            </CartProvider>
          </AuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
